### ISSUE TITLE
WARN  No layout: index.html

### ISSUE THREAD

**Issue by M-suny** [xiangming/xiangming.github.com#1]
pull master -->  hexo g --> hexo s
![image](https://cloud.githubusercontent.com/assets/11222639/15797167/c30c6bee-2a41-11e6-9296-de4092cecf64.png)

在本地浏览的时候，浏览器就是空白页。
WARN  No layout: index.html

thems 下面是有 xiangming的~
![image](https://cloud.githubusercontent.com/assets/11222639/15797190/6ea32dd0-2a42-11e6-8a3d-d70f1ac2fa49.png)

**Comment by xiangming** [comment]
@M-suny 
参考这个项目介绍操作。
